### ISSUE TITLE
Délégation d'utilisation Homebridge

### ISSUE THREAD

**Issue by neuralldev** [jeedom/homebridge-jeedom#10]
Lorsque l'on est plusieurs à domicile et qu'on autorise une autre personne à utiliser la configuration que l'on a créé (liste des objets), la personne reçoit bien l'invitation, le domicile s'ajoute, mais il n'arrive pas à voir le contrôleur jeedom (ne répond pas). 

Faut-il enregistrer ou pas l'autre utilisateur et comment ? à détailler !

**Comment by rocket13011** [comment]
ce n'est pas le faite de homebridge, ni de homebridge-Jeedom, c'est sur homekit : https://support.apple.com/fr-fr/HT204893

**Comment by neuralldev** [comment]
Donc il faut impérativement un concentrateur ... ok reçu.
