### ISSUE TITLE
Impossible de lancer le démon homebridge, relancer le démon en debug et vérifiez la log

### ISSUE THREAD

**Issue by Jeedom50** [jeedom/homebridge-jeedom#12]
0

**Comment by magicgg91** [comment]
Bonjour, tu as essayé de lancer la commande donnée dans la log ?? C'est bien de faire une issue pour une prblème, mais c'est encore mieux de lire les éléments fournis :)

sudo apt-get update

**Comment by Jeedom50** [comment]
Alors la ... tu me parles chinois ... si tu connais un tuto détaillé, je suis preneur, car je suis à la ramasse, je débute sur jeedom, j'avance doucement, mais le je plante sur ce problème depuis 3 jours ...
Merci :)

**Comment by Jeedom50** [comment]
J'ai cliqué sur réparé dans gestion des plugins / appmobile le homebridge passe au vert, puis une minute après, stautut NOK, homebridge passe en rouge
Il y a un tuto pour les nuls ? ;)

**Comment by nechry** [comment]
il faudrait lancer en ligne de commande (ssh) 
`sudo apt-get update`
puis lancer a nouveau la mise a jour des dépendances.

La section issues est pour rapporter des erreurs dans sur homebridge-jeedom. merci d'utiliser le forum jeedom pour des demandes de supports.

**Comment by Jeedom50** [comment]
OK, merci pour l'info, ça marche enfin ! super
J'ai effacé le contenu, car je ne sais pas si des infos était confidentielles pour mon installation
Merci encore
