### ISSUE TITLE
Ne marche pas si Jeedom pas local sur port 80

### ISSUE THREAD

**Issue by ojacques** [jeedom/homebridge-jeedom#9]
A causse de [ce commit](https://github.com/jeedom/homebridge-jeedom/commit/1b54b240d0f509645119a0421c8e5e1f15802719), homebridge ne peut pas contacter un jeedom qui écoute sur autre chose que 127.0.0.1:80 (en local, sur le port 80).

Je pense qu'il faut revenir en arrière ❓ 

En attendant, si Jeedom est sur le même host que homebridge, une façon de s'en sortir est d'éditer le fichier `/etc/apache2/ports.conf` et rajouter une ligne `Listen 80` permettra à Jeedom d'écouter sur le port 80 en plus du port d'origine, et ainsi de faire fonctionner homebridge.

La liste des commandes:
```
sudo vi /etc/apache2/ports.conf
sudo systemctl daemon-reload
sudo /etc/init.d/apache2 restart
```

**Comment by ojacques** [comment]
@rocket13011 - tu en penses quoi ?

**Comment by rocket13011** [comment]
Plus facile :
sudo npm install -g https://github.com/jeedom/homebridge-jeedom.git#Docker

Plus facile ;)
Bientôt de nouveau dispo dans la version stable Avec un nouveau plugin qui refait toute la partie synchro de homebridge ;)

**Comment by NebzHB** [comment]
Est résolu dans la prochaine version, on prend la valeur de config de Jeedom
